def help():
	print("Este paint soporta los siguientes comandos: ")
	print("Para dibujar debes de escribir los mandos de siguiente manera: ")
	print("comando -t c g x y")
	print("c= color del que quieres el trazo")
	print("g= grosor del que quieres el trazo")
	print("x= es la posicion x del trazo")
	print("y= es la posicion y del trazo")
	print("debes remplazar las anteriores variables con numeros")
	print("comando -triangulo= se usa para dibujar un triangulo")
	print("comando -rectanguloh= se usa para dibujar un rectangulo horizontal")
	print("comando -rectangulov= se usa para dibujar un rectangulo vertical")
	print("comando -cuadrado= se usa para dibujar un cuadrado")
	print("comando -colores= se usa para listar los colores soportados")
	print("comando -linea= se usa para dibujar una linea")
	print("para usar el comando -l se usa de la siguiente manera: ")
	print("comando -l c g x y x2 y2")
	print("al usar este comando tendras que agregar 2 cordenadas mas")
